#!/bin/bash
#A simple script that auto-compresses the Doug user directory and writes it to

## Remember to ready this file with chmod 755(linux) or your system's equivalent#############################################

UPDATEDIR="$HOME/Dropbox/Backups"

if [ "$1" = "--keybase" ]
  then
    if [ -n "$2" ]
      then
        UPDATEDIR="/keybase/private/$2"
      else
        echo "No keybase username given!"
        echo "usage: update --keybase USERNAME"
        exit 1
    fi
fi
echo "Running weekly updates..."

#First move Week 1 to Week 2
echo "Pushing back old data..."
mv $UPDATEDIR/Week1/* $UPDATEDIR/Week2

#now update the week 1 archives 1 directory at a time
echo "Storing this week's data..."

#Documents
echo "Backing up Documents..."
#7z u $UPDATEDIR/Week1/docs.7z $HOME/Documents

#Music
echo "Backing up Music..."
#7z u $UPDATEDIR/Week1/mus.7z $HOME/Music
#RAR is occaisionally used for superior MP3 performance... but it is no significant difference on a machine with little to no music

#Pictures
echo "Backing up Pictures..."
7z u $UPDATEDIR/Week1/pics.7z $HOME/Pictures

#Videos
echo "Backing up Videos..."
#7z u $UPDATEDIR/Week1/vids.7z $HOME/Videos

#Programs
##Maybe this isn't necessary...############################
#"Backing up user-identified programs..."
#7z u $HOME/Dropbox/Backups/Week1/progs.7z
